### ISSUE TITLE
Integrate INLA model class

### ISSUE THREAD

**Issue by JamesYang007** [Confirm-Solutions/kevlar#11]
Biggest feature for the first prototype!

- [x] Implement the INLA model class
- [x] Write example python script similar to the one for Binomial
- [ ] Figure out toggleable parameters for Gary to play around with

**Comment by tbenthompson** [comment]
I'm going to close this since we have lots of kevlar+inla stuff happening these days! I'm not sure what the goal was for the last bullet point, but it doesn't seem like a priority right now.
