### ISSUE TITLE
Benchmark and add tcmalloc

### ISSUE THREAD

**Issue by constinit** [Confirm-Solutions/kevlar#64]
tcmalloc could potentially decrease the cost of dynamic memory allocation and improve hugepage usage.

It may take some tuning:
https://github.com/google/tcmalloc/blob/master/docs/tuning.md

It also doesn't build on mac, so it will need to be flag configurable in the build:
https://docs.bazel.build/versions/main/configurable-attributes.html

**Comment by tbenthompson** [comment]
I lean towards closing this or moving it into a doc that stores tips and ideas for optimization. I don't expect most of our long-term performance problems to involve allocation. For example, the Berry+INLA code is entirely flop-limited.

**Comment by constinit** [comment]
Fair, allocation may no longer be on the critical path with Jax.
